window.localRoutes = [
  {
    id: "beijing-0816-station-hotel",
    dayId: "beijing-2026-08-16",
    order: 1,
    fromStopId: "beijing-0816-station-arrival",
    toStopId: "beijing-0816-hotel-arrival",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "14-17 km",
    estimatedDuration: "35-55 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "beijing-0816-hotel-tiananmen",
    dayId: "beijing-2026-08-16",
    order: 2,
    fromStopId: "beijing-0816-hotel-arrival",
    toStopId: "beijing-0816-tiananmen-square",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "7-9 km",
    estimatedDuration: "25-40 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "beijing-0816-tiananmen-forbidden",
    dayId: "beijing-2026-08-16",
    order: 3,
    fromStopId: "beijing-0816-tiananmen-square",
    toStopId: "beijing-0816-forbidden-city",
    mode: "walk",
    modeLabel: "Walk",
    distance: "1-1.5 km",
    estimatedDuration: "20-30 minutes including security checks",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "beijing-0816-forbidden-jingshan",
    dayId: "beijing-2026-08-16",
    order: 4,
    fromStopId: "beijing-0816-forbidden-city",
    toStopId: "beijing-0816-jingshan-park",
    mode: "walk",
    modeLabel: "Walk",
    distance: "400 m",
    estimatedDuration: "5-10 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "beijing-0816-jingshan-corner",
    dayId: "beijing-2026-08-16",
    order: 5,
    fromStopId: "beijing-0816-jingshan-park",
    toStopId: "beijing-0816-corner-tower",
    mode: "walk",
    modeLabel: "Walk",
    distance: "1.2-1.4 km",
    estimatedDuration: "15-20 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "beijing-0816-corner-wangfujing",
    dayId: "beijing-2026-08-16",
    order: 6,
    fromStopId: "beijing-0816-corner-tower",
    toStopId: "beijing-0816-wangfujing-dinner",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "3-4 km",
    estimatedDuration: "15-25 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "beijing-0816-wangfujing-hotel",
    dayId: "beijing-2026-08-16",
    order: 7,
    fromStopId: "beijing-0816-wangfujing-dinner",
    toStopId: "beijing-0816-hotel-return",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "6-8 km",
    estimatedDuration: "20-35 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "beijing-0817-hotel-mutianyu",
    dayId: "beijing-2026-08-17",
    order: 1,
    fromStopId: "beijing-0817-hotel-departure",
    toStopId: "beijing-0817-mutianyu-visitor-center",
    mode: "private-car",
    modeLabel: "Prebooked private car",
    distance: "65-75 km",
    estimatedDuration: "1 hour 20 minutes-1 hour 50 minutes",
    routeStatus: "Estimated",
    lineStyle: "thick"
  },
  {
    id: "beijing-0817-visitor-center-wall",
    dayId: "beijing-2026-08-17",
    order: 2,
    fromStopId: "beijing-0817-mutianyu-visitor-center",
    toStopId: "beijing-0817-mutianyu-exploration",
    mode: "shuttle",
    modeLabel: "Shuttle + chairlift sequence",
    distance: "Approximate scenic-area transfer",
    estimatedDuration: "20-30 minutes plus queue",
    routeStatus: "Estimated",
    lineStyle: "solid"
  },
  {
    id: "beijing-0817-wall-lunch",
    dayId: "beijing-2026-08-17",
    order: 3,
    fromStopId: "beijing-0817-mutianyu-exploration",
    toStopId: "beijing-0817-mutianyu-lunch",
    mode: "toboggan",
    modeLabel: "Toboggan + short walk",
    distance: "Ride down from the wall",
    estimatedDuration: "5-10 minutes plus queue",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "beijing-0817-lunch-hotel",
    dayId: "beijing-2026-08-17",
    order: 4,
    fromStopId: "beijing-0817-mutianyu-lunch",
    toStopId: "beijing-0817-hotel-rest",
    mode: "private-car",
    modeLabel: "Prebooked private car",
    distance: "65-75 km",
    estimatedDuration: "1 hour 30 minutes-2 hours 30 minutes",
    routeStatus: "Estimated",
    lineStyle: "thick"
  },
  {
    id: "beijing-0817-hotel-sanlitun",
    dayId: "beijing-2026-08-17",
    order: 5,
    fromStopId: "beijing-0817-hotel-rest",
    toStopId: "beijing-0817-sanlitun-dinner",
    mode: "walk",
    modeLabel: "Walk",
    distance: "500 m-1.5 km",
    estimatedDuration: "10-20 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "beijing-0818-hotel-summer-palace",
    dayId: "beijing-2026-08-18",
    order: 1,
    fromStopId: "beijing-0818-hotel-departure",
    toStopId: "beijing-0818-summer-palace",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "25-30 km",
    estimatedDuration: "45-70 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "beijing-0818-summer-old-summer",
    dayId: "beijing-2026-08-18",
    order: 2,
    fromStopId: "beijing-0818-summer-palace",
    toStopId: "beijing-0818-old-summer-palace",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "4-6 km",
    estimatedDuration: "15-25 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "beijing-0818-old-summer-lunch",
    dayId: "beijing-2026-08-18",
    order: 3,
    fromStopId: "beijing-0818-old-summer-palace",
    toStopId: "beijing-0818-yuanmingyuan-lunch",
    mode: "walk",
    modeLabel: "Walk",
    distance: "Short exit toward lunch",
    estimatedDuration: "5-10 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "beijing-0818-lunch-798",
    dayId: "beijing-2026-08-18",
    order: 4,
    fromStopId: "beijing-0818-yuanmingyuan-lunch",
    toStopId: "beijing-0818-art-798",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "24-28 km",
    estimatedDuration: "45-70 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "beijing-0818-798-sanlitun",
    dayId: "beijing-2026-08-18",
    order: 5,
    fromStopId: "beijing-0818-art-798",
    toStopId: "beijing-0818-sanlitun-dinner",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "10-13 km",
    estimatedDuration: "25-45 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "beijing-0818-sanlitun-hotel",
    dayId: "beijing-2026-08-18",
    order: 6,
    fromStopId: "beijing-0818-sanlitun-dinner",
    toStopId: "beijing-0818-hotel-return",
    mode: "walk",
    modeLabel: "Walk or short DiDi",
    distance: "Short hotel return",
    estimatedDuration: "10-20 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "beijing-0819-hotel-temple",
    dayId: "beijing-2026-08-19",
    order: 1,
    fromStopId: "beijing-0819-hotel-departure",
    toStopId: "beijing-0819-temple-of-heaven",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "9-11 km",
    estimatedDuration: "25-40 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "beijing-0819-temple-museum",
    dayId: "beijing-2026-08-19",
    order: 2,
    fromStopId: "beijing-0819-temple-of-heaven",
    toStopId: "beijing-0819-national-museum",
    mode: "subway",
    modeLabel: "Subway Line 5 + Line 1",
    distance: "5-7 km",
    estimatedDuration: "25-35 minutes",
    routeStatus: "Estimated",
    lineStyle: "solid"
  },
  {
    id: "beijing-0819-museum-lunch",
    dayId: "beijing-2026-08-19",
    order: 3,
    fromStopId: "beijing-0819-national-museum",
    toStopId: "beijing-0819-quick-lunch",
    mode: "walk",
    modeLabel: "Walk",
    distance: "Short lunch transition",
    estimatedDuration: "5-10 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "beijing-0819-lunch-ancient-monarchs",
    dayId: "beijing-2026-08-19",
    order: 4,
    fromStopId: "beijing-0819-quick-lunch",
    toStopId: "beijing-0819-ancient-monarchs",
    mode: "subway",
    modeLabel: "Line 1 + Line 2",
    distance: "6-7 km",
    estimatedDuration: "30-40 minutes",
    routeStatus: "Estimated",
    lineStyle: "solid"
  },
  {
    id: "beijing-0819-ancient-monarchs-white-pagoda",
    dayId: "beijing-2026-08-19",
    order: 5,
    fromStopId: "beijing-0819-ancient-monarchs",
    toStopId: "beijing-0819-white-pagoda",
    mode: "walk",
    modeLabel: "Walk",
    distance: "400-600 m",
    estimatedDuration: "6-10 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "beijing-0819-white-pagoda-towers",
    dayId: "beijing-2026-08-19",
    order: 6,
    fromStopId: "beijing-0819-white-pagoda",
    toStopId: "beijing-0819-drum-bell-towers",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "5-6 km",
    estimatedDuration: "20-30 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "beijing-0819-towers-shichahai",
    dayId: "beijing-2026-08-19",
    order: 7,
    fromStopId: "beijing-0819-drum-bell-towers",
    toStopId: "beijing-0819-shichahai-hutongs",
    mode: "walk",
    modeLabel: "Walk",
    distance: "1-2 km",
    estimatedDuration: "20-30 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "beijing-0819-shichahai-beihai",
    dayId: "beijing-2026-08-19",
    order: 8,
    fromStopId: "beijing-0819-shichahai-hutongs",
    toStopId: "beijing-0819-beihai-park",
    mode: "walk",
    modeLabel: "Walk",
    distance: "1.2-1.8 km",
    estimatedDuration: "15-25 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "beijing-0819-beihai-hotel",
    dayId: "beijing-2026-08-19",
    order: 9,
    fromStopId: "beijing-0819-beihai-park",
    toStopId: "beijing-0819-hotel-return",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "7-9 km",
    estimatedDuration: "25-40 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "shanghai-0822-hotel-people-square",
    dayId: "shanghai-2026-08-22",
    order: 1,
    fromStopId: "shanghai-0822-hotel-arrival",
    toStopId: "shanghai-0822-people-square",
    mode: "flexible",
    modeLabel: "Walk / Metro Line 2 / short DiDi",
    distance: "Hotel-dependent",
    estimatedDuration: "5-20 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "shanghai-0822-people-square-nanjing",
    dayId: "shanghai-2026-08-22",
    order: 2,
    fromStopId: "shanghai-0822-people-square",
    toStopId: "shanghai-0822-nanjing-road",
    mode: "walk",
    modeLabel: "Walk",
    distance: "Short west-end transition",
    estimatedDuration: "5-10 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0822-nanjing-bund",
    dayId: "shanghai-2026-08-22",
    order: 3,
    fromStopId: "shanghai-0822-nanjing-road",
    toStopId: "shanghai-0822-the-bund",
    mode: "walk",
    modeLabel: "Walk",
    distance: "Approximately 1.5-2 km",
    estimatedDuration: "25-35 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0822-bund-dinner",
    dayId: "shanghai-2026-08-22",
    order: 4,
    fromStopId: "shanghai-0822-the-bund",
    toStopId: "shanghai-0822-bund-dinner",
    mode: "walk",
    modeLabel: "Walk",
    distance: "Short riverfront dinner transition",
    estimatedDuration: "10-15 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0822-dinner-hotel",
    dayId: "shanghai-2026-08-22",
    order: 5,
    fromStopId: "shanghai-0822-bund-dinner",
    toStopId: "shanghai-0822-hotel-return",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "Central Puxi return",
    estimatedDuration: "10-25 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "shanghai-0823-hotel-yu-garden",
    dayId: "shanghai-2026-08-23",
    order: 1,
    fromStopId: "shanghai-0823-hotel-departure",
    toStopId: "shanghai-0823-yu-garden",
    mode: "metro",
    modeLabel: "Metro Line 10 or DiDi",
    distance: "3-6 km",
    estimatedDuration: "15-30 minutes",
    routeStatus: "Estimated",
    lineStyle: "solid"
  },
  {
    id: "shanghai-0823-yu-garden-city-god",
    dayId: "shanghai-2026-08-23",
    order: 2,
    fromStopId: "shanghai-0823-yu-garden",
    toStopId: "shanghai-0823-city-god-temple",
    mode: "walk",
    modeLabel: "Walk",
    distance: "200-400 m",
    estimatedDuration: "5 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0823-city-god-lunch",
    dayId: "shanghai-2026-08-23",
    order: 3,
    fromStopId: "shanghai-0823-city-god-temple",
    toStopId: "shanghai-0823-yuyuan-lunch",
    mode: "walk",
    modeLabel: "Walk",
    distance: "Inside the bazaar area",
    estimatedDuration: "5-10 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0823-lunch-greenhouse",
    dayId: "shanghai-2026-08-23",
    order: 4,
    fromStopId: "shanghai-0823-yuyuan-lunch",
    toStopId: "shanghai-0823-greenhouse-garden",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "8-10 km",
    estimatedDuration: "25-35 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "shanghai-0823-greenhouse-dinner",
    dayId: "shanghai-2026-08-23",
    order: 5,
    fromStopId: "shanghai-0823-greenhouse-garden",
    toStopId: "shanghai-0823-riverfront-dinner",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "9-12 km",
    estimatedDuration: "25-40 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "shanghai-0823-dinner-pier",
    dayId: "shanghai-2026-08-23",
    order: 6,
    fromStopId: "shanghai-0823-riverfront-dinner",
    toStopId: "shanghai-0823-shiliupu-pier",
    mode: "walk",
    modeLabel: "Walk",
    distance: "5-15 minutes",
    estimatedDuration: "5-15 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0823-pier-cruise",
    dayId: "shanghai-2026-08-23",
    order: 7,
    fromStopId: "shanghai-0823-shiliupu-pier",
    toStopId: "shanghai-0823-huangpu-cruise",
    mode: "boat",
    modeLabel: "Boarding to cruise",
    distance: "Pier embarkation",
    estimatedDuration: "Queue and boarding",
    routeStatus: "Estimated",
    lineStyle: "solid"
  },
  {
    id: "shanghai-0823-cruise-bund",
    dayId: "shanghai-2026-08-23",
    order: 8,
    fromStopId: "shanghai-0823-huangpu-cruise",
    toStopId: "shanghai-0823-bund-final-walk",
    mode: "walk",
    modeLabel: "Walk",
    distance: "Short riverfront continuation",
    estimatedDuration: "5-10 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0823-bund-hotel",
    dayId: "shanghai-2026-08-23",
    order: 9,
    fromStopId: "shanghai-0823-bund-final-walk",
    toStopId: "shanghai-0823-hotel-return",
    mode: "taxi",
    modeLabel: "DiDi or Metro Line 2/10",
    distance: "Central Puxi return",
    estimatedDuration: "15-30 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "shanghai-0824-hotel-disney",
    dayId: "shanghai-2026-08-24",
    order: 1,
    fromStopId: "shanghai-0824-hotel-departure",
    toStopId: "shanghai-0824-disney-entry",
    mode: "metro",
    modeLabel: "Metro ending on Line 11",
    distance: "Approximate cross-city trip",
    estimatedDuration: "60-75 minutes",
    routeStatus: "Estimated",
    lineStyle: "solid"
  },
  {
    id: "shanghai-0824-entry-park",
    dayId: "shanghai-2026-08-24",
    order: 2,
    fromStopId: "shanghai-0824-disney-entry",
    toStopId: "shanghai-0824-disneyland",
    mode: "walk",
    modeLabel: "Park entry",
    distance: "Gate-to-park transition",
    estimatedDuration: "10-20 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0824-disney-hotel",
    dayId: "shanghai-2026-08-24",
    order: 3,
    fromStopId: "shanghai-0824-disneyland",
    toStopId: "shanghai-0824-hotel-return",
    mode: "metro",
    modeLabel: "Line 11 or prearranged DiDi",
    distance: "Approximate cross-city return",
    estimatedDuration: "60-90 minutes",
    routeStatus: "Estimated",
    lineStyle: "solid"
  },
  {
    id: "shanghai-0825-hotel-shanghai-station",
    dayId: "shanghai-2026-08-25",
    order: 1,
    fromStopId: "shanghai-0825-hotel-departure",
    toStopId: "shanghai-0825-shanghai-station-outbound",
    mode: "taxi",
    modeLabel: "DiDi",
    distance: "3-7 km",
    estimatedDuration: "15-25 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "shanghai-0825-shanghai-suzhou-train",
    dayId: "shanghai-2026-08-25",
    order: 2,
    fromStopId: "shanghai-0825-shanghai-station-outbound",
    toStopId: "shanghai-0825-suzhou-station-arrival",
    mode: "train",
    modeLabel: "High-speed train",
    distance: "Intercity rail",
    estimatedDuration: "25-35 minutes",
    routeStatus: "Estimated",
    lineStyle: "solid"
  },
  {
    id: "shanghai-0825-suzhou-station-garden",
    dayId: "shanghai-2026-08-25",
    order: 3,
    fromStopId: "shanghai-0825-suzhou-station-arrival",
    toStopId: "shanghai-0825-humble-garden",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "4-5 km",
    estimatedDuration: "15-20 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "shanghai-0825-garden-pingjiang",
    dayId: "shanghai-2026-08-25",
    order: 4,
    fromStopId: "shanghai-0825-humble-garden",
    toStopId: "shanghai-0825-pingjiang-road",
    mode: "walk",
    modeLabel: "Walk",
    distance: "500-800 m",
    estimatedDuration: "5-10 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0825-pingjiang-lunch",
    dayId: "shanghai-2026-08-25",
    order: 5,
    fromStopId: "shanghai-0825-pingjiang-road",
    toStopId: "shanghai-0825-suzhou-lunch",
    mode: "walk",
    modeLabel: "Walk",
    distance: "Short canal-side continuation",
    estimatedDuration: "5-10 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0825-lunch-suzhou-station",
    dayId: "shanghai-2026-08-25",
    order: 6,
    fromStopId: "shanghai-0825-suzhou-lunch",
    toStopId: "shanghai-0825-suzhou-station-return",
    mode: "taxi",
    modeLabel: "DiDi/taxi",
    distance: "4-5 km",
    estimatedDuration: "15-20 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "shanghai-0825-suzhou-shanghai-train",
    dayId: "shanghai-2026-08-25",
    order: 7,
    fromStopId: "shanghai-0825-suzhou-station-return",
    toStopId: "shanghai-0825-shanghai-station-return",
    mode: "train",
    modeLabel: "High-speed train",
    distance: "Intercity rail",
    estimatedDuration: "25-35 minutes",
    routeStatus: "Estimated",
    lineStyle: "solid"
  },
  {
    id: "shanghai-0825-station-jingan",
    dayId: "shanghai-2026-08-25",
    order: 8,
    fromStopId: "shanghai-0825-shanghai-station-return",
    toStopId: "shanghai-0825-jingan-temple",
    mode: "taxi",
    modeLabel: "DiDi or metro",
    distance: "4-5 km",
    estimatedDuration: "15-30 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "shanghai-0825-jingan-anfu",
    dayId: "shanghai-2026-08-25",
    order: 9,
    fromStopId: "shanghai-0825-jingan-temple",
    toStopId: "shanghai-0825-anfu-road",
    mode: "taxi",
    modeLabel: "DiDi",
    distance: "4-5 km",
    estimatedDuration: "15-25 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "shanghai-0825-anfu-wukang",
    dayId: "shanghai-2026-08-25",
    order: 10,
    fromStopId: "shanghai-0825-anfu-road",
    toStopId: "shanghai-0825-wukang-road",
    mode: "walk",
    modeLabel: "Walk",
    distance: "Approximately 1 km",
    estimatedDuration: "15-20 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0825-wukang-road-mansion",
    dayId: "shanghai-2026-08-25",
    order: 11,
    fromStopId: "shanghai-0825-wukang-road",
    toStopId: "shanghai-0825-wukang-mansion",
    mode: "walk",
    modeLabel: "Walk",
    distance: "Short continuation south",
    estimatedDuration: "10-15 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0825-mansion-french-concession",
    dayId: "shanghai-2026-08-25",
    order: 12,
    fromStopId: "shanghai-0825-wukang-mansion",
    toStopId: "shanghai-0825-french-concession-dinner",
    mode: "walk",
    modeLabel: "Walk",
    distance: "Approximately 2-3 km",
    estimatedDuration: "30-40 minutes",
    routeStatus: "Estimated",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0825-french-concession-hotel",
    dayId: "shanghai-2026-08-25",
    order: 13,
    fromStopId: "shanghai-0825-french-concession-dinner",
    toStopId: "shanghai-0825-hotel-return",
    mode: "taxi",
    modeLabel: "DiDi",
    distance: "Central city return",
    estimatedDuration: "10-25 minutes",
    routeStatus: "Estimated",
    lineStyle: "dashed"
  },
  {
    id: "shanghai-0826-hotel-breakfast",
    dayId: "shanghai-2026-08-26",
    order: 1,
    fromStopId: "shanghai-0826-hotel-checkout",
    toStopId: "shanghai-0826-breakfast-walk",
    mode: "walk",
    modeLabel: "Walk",
    distance: "Nearby wandering only",
    estimatedDuration: "10-20 minutes",
    routeStatus: "Editable",
    lineStyle: "dotted"
  },
  {
    id: "shanghai-0826-breakfast-airport",
    dayId: "shanghai-2026-08-26",
    order: 2,
    fromStopId: "shanghai-0826-breakfast-walk",
    toStopId: "shanghai-0826-airport-transfer",
    mode: "taxi",
    modeLabel: "Airport transfer",
    distance: "Airport-dependent",
    estimatedDuration: "Editable after booking",
    routeStatus: "Editable",
    lineStyle: "dashed"
  },
  {
    id: "shanghai-0826-airport-flight",
    dayId: "shanghai-2026-08-26",
    order: 3,
    fromStopId: "shanghai-0826-airport-transfer",
    toStopId: "shanghai-0826-new-york-flight",
    mode: "flight",
    modeLabel: "International departure",
    distance: "Editable after booking",
    estimatedDuration: "Editable after booking",
    routeStatus: "Editable",
    lineStyle: "curved"
  }
];
